<?php

namespace Application\Repository;

/**
 * Staff
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Staff extends \Doctrine\ORM\EntityRepository
{
}
