<?php

namespace Application\Repository;

/**
 * Unit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Unit extends \Doctrine\ORM\EntityRepository
{
}
