<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Allianz Worldwide Partners')->setSeparator(' / ')->setAutoEscape(false) . PHP_EOL; ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') . PHP_EOL;
        ?>

        <!-- Le styles -->
        <link href="/assets/images/favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <?php echo $this->headLink()
                ->prependStylesheet($this->basePath('/assets/css/style.css'))
                ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900')
                ->prependStylesheet($this->basePath('/assets/bower_components/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('/assets/bower_components/bootstrap/dist/css/bootstrap.min.css'))
                . PHP_EOL; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->basePath('/assets/bower_components/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('/assets/bower_components/jquery/dist/jquery.min.js'))
                ->appendFile($this->basePath('/assets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath('/assets/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)) . PHP_EOL;
        ?>
    </head>
    <body>
        <div class="container">
            <header>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <img src="<?php echo $this->basePath('/assets/images/logo_awp.jpg');?>">
                    </div>
                </div>
            </header>

            <section class="content">
                <div class="row">
                    <div class="col-md-12">
<!-- BEGIN CONTENT -->

<?php echo $this->content; ?>

<!-- END CONTENT -->

                    </div>
                </div>
            </section>

            <footer>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="row">
                            <div class="col-md-8">
                                © Copyright <?php echo date('Y');?> Allianz Worldwide Partners.
                            </div>
                            <div class="col-md-4">
                                <img src="<?php echo $this->basePath('/assets/images/logo_awp_footer.jpg');?>" class="pull-right">
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

        </div>
        <?php echo $this->inlineScript() ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-70879037-2', 'auto');
            ga('send', 'pageview');

        </script>
    </body>
</html>
