<?php
    $form = $this->form;
    $form->prepare();
?>
<div class="row">
    <div class="col-md-6 col-lg-offset-3">

        <div class="pg_form">
            <section>
                <div class="row">
                    <div class="col-md-12">
                        <img src="<?php echo $this->basePath('/assets/images/banner.jpg');?>" class="img-responsive">
                    </div>
                    <div class="col-md-12">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p>
                            Pequenas atitudes podem mudar o seu dia.
                        </p>
                        <p>
                            Não deixe que elas passem em branco.
                        </p>
                        <p>
                            Tome atitude, reconheça!
                        </p>
                    </div>
                </div>
            </section>

            <section>
<?php echo $this->form()->openTag($form) . PHP_EOL; ?>
<?php
    foreach($form->getElements() as $element):
?>
<?php echo $this->formRow($element) . PHP_EOL;?>
<?php
    endforeach;
?>
<?php
    foreach($form->getFieldsets() as $fieldset):
?>
                    <fieldset>
                        <legend><?php echo $fieldset->getLabel();?></legend>
<?php
        foreach($fieldset->getElements() as $element):
?>
                            <div class="form-group<?php if($this->formElementErrors($element)):?> has-error<?php endif;?>">
                                <?php echo $this->formLabel($element) . PHP_EOL; ?>
                                <div class="col-<?php echo $element->getOptions()['column-size'];?>">
                                    <?php echo $this->formElement($element) . PHP_EOL;?>
                                </div><?php echo $this->formElementErrors()
                                        ->setMessageOpenFormat('<div class="col-md-9 col-md-offset-3"><div class="help-inline">')
                                        ->setMessageSeparatorString('</div><div class="help-inline">')
                                        ->setMessageCloseString('</div></div>')
                                        ->render($element) . PHP_EOL; ?>
                            </div>
<?php
        endforeach;
?>
                    </fieldset>
<?php
    endforeach;
?>
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-default pull-right">ENVIAR</button>
                        </div>
                    </div>
<?php echo $this->form()->closeTag() . PHP_EOL; ?>
            </section>
        </div>

    </div>
</div>