<div class="row">
    <div class="col-md-6 col-lg-offset-3">

        <div class="pg_thankyou">
            <section>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h1>OBRIGADO</h1>
                        <p>
                            Sua mensagem foi enviada com sucesso.
                        </p>
                        <p>
                            Após a moderação, sua mensagem será ser divulgada.
                        </p>
                    </div>
                </div>
            </section>
        </div>

    </div>
</div>